### ISSUE TITLE
Sandbox example pages are blank

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/WhatsNearby#1]
Back in Feb I created some examples [0, 1] but the pages are going blank. @kghbln Do we have any log messages?

[0] http://sandbox.semantic-mediawiki.org/wiki/Whats_Nearby/GoogleMaps_%28no_geolocation_detection%29
[1] http://sandbox.semantic-mediawiki.org/wiki/Whats_Nearby/No_location_information

**Comment by kghbln** [comment]
> Do we have any log messages?

Yes, it's the same for both pages: 
```text
PHP Fatal error:  Class 'WNBY\\NearByParserFunction' not found in /.../w/extensions/WhatsNearby/src/ParserFunctionFactory.php on line 22
```

**Comment by mwjames** [comment]
> PHP Fatal error:  Class 'WNBY\\NearByParserFunction' not found in /.../w/extensions/WhatsNearby/src/ParserFunctionFactory.php on line 22

I know why, because of the lower/upper case of `NearByP` (on WIN that doesn't matter) ...!!!!!

**Comment by mwjames** [comment]
> because of the lower/upper case of 

... and fixed with #2.

**Comment by kghbln** [comment]
Just updated sandbox.

**Comment by mwjames** [comment]
> Just updated sandbox.

Awesome service.
