### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/WhatsNearby#15]
https://travis-ci.org/SemanticMediaWiki/WhatsNearby/jobs/280181118

Looks like the CI failures are due to too old PHPUnit

I ran into this for SemanticWatchlist some days ago and fixed it there with SemanticMediaWiki/SemanticWatchlist#83, which also simplifies the CI code

**Comment by kghbln** [comment]
Fixed with https://github.com/SemanticMediaWiki/WhatsNearby/pull/18
