### ISSUE TITLE
Get i18n rolling

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/WhatsNearby#3]
* [x] Set up I18n-mirror - Requested at https://www.mediawiki.org/wiki/Git/New_repositories/Requests
* [x]  Fluff message documentation - https://github.com/SemanticMediaWiki/WhatsNearby/pull/7
* [x] Ping tw.n - [T131846](https://phabricator.wikimedia.org/T131846)

**Comment by kghbln** [comment]
This is tragic. I pushed a new branch but it ended up in void. GitHub tells me via the shell that the new branch is there and up to date and and the same time fails to show this branch here. Perhaps it re-emerges. If not I will try again theses days.

**Comment by mwjames** [comment]
>I pushed a new branch but it ended up in void. GitHub tells me via the shell that the new branch is there and up to date

@kghbln How about?

![image](https://cloud.githubusercontent.com/assets/1245473/14277550/ebc721ca-fb23-11e5-8ae8-f79b7810e0c2.png)

**Comment by kghbln** [comment]
> How about?

Well this one was not there before. Now the issue is that no diff `0|0` can be tetected. So this stuff is lost. I will try something.

**Comment by kghbln** [comment]
Nope, everything is lost. The diff just does not get to GitHub. Will do another one soon.

**Comment by kghbln** [comment]
Here we are. Lessons learned. Do not push when GitHub is down. Still cool to have them.

**Comment by JeroenDeDauw** [comment]
Unless you did something weird, your local git should still have it. And even if you did something weird, git might still have it, although in a way that is not as easy to extract

**Comment by kghbln** [comment]
> your local git should still have it.

That's why I was able to do it again today. All fluffy now. :)

**Comment by kghbln** [comment]
All done thanks to @siebrand
